<a href="https://colab.research.google.com/github/usmankhawar22/Machine-Learning/blob/master/Lab4_UK_208775.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1

In [0]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1
    if (iter % 1000) == 0:
        print("Error:" + str(np.mean(np.abs(l1_error))))
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)


Error:0.5172082754380926
Error:0.026070259693142646
Error:0.0181554678525527
Error:0.014723482568835052
Error:0.012699314779145614
Error:0.011327232073339398
Error:0.010319216334688502
Error:0.009538603095349355
Error:0.00891115763147092
Error:0.008392641900637663
Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


# Task 2

In [17]:
import numpy as np
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
# input dataset
X = np.array([  [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])

y = np.array([[0,1,1,0]]).T
# set seed
np.random.seed(1)
# initialize weights
syn0 = 2*np.random.random((3,4)) - 1        #4 neurons in the next layer
syn1 = 2*np.random.random((4,3)) - 1          # 3 neorons in next layer
syn2 = 2*np.random.random((3,1)) - 1          #output layer
for j in range(60000):
# forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l3 = nonlin(np.dot(l2,syn2))
    

    # how much did we miss the target value?
    
    l3_error = y-l3
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l3_error))))
    
    l3_delta = l3_error*nonlin(l3, deriv=True)
    
    l2_error = l3_delta.dot(syn2.T)

    
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    syn2 += l2.T.dot(l3_delta)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("Output After Training:")
print(l3)


Error:0.49891152856875803
Error:0.005582339859512456
Error:0.003771532088094244
Error:0.0030149394938018123
Error:0.0025765790370416083
Error:0.002282812569060292
Output After Training:
[[0.00171855]
 [0.99820493]
 [0.99766227]
 [0.00242384]]


# Task 3

In [14]:
import numpy as np
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
# input dataset
X = np.array([[0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])
y = np.array([[0,1], [1,0], [1,0], [0,1]])
# set seed
np.random.seed(1)
# initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,2)) - 1
for j in range(60000):
# forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))         #syn is for activation of previous layer
    
    # how much did we miss the target value?
    l2_error = y - l2

    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print("Output After Training:")
print(l2)

print(np.argmax(l2,axis=1))

Error:0.49954519056925606
Error:0.009627549726006376
Error:0.006584574553539306
Error:0.005299966814471063
Error:0.0045510990523981824
Error:0.004047010847593672
Output After Training:
[[0.00296225 0.99703923]
 [0.99808538 0.00191443]
 [0.99522702 0.00477115]
 [0.00506651 0.99493483]]
[1 0 0 1]


# Task 4

In [27]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

    
X = np.arange(0,4.2,0.2).reshape(21,1)

y = nonlin(X)

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((1,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

print ("Output After Training:")
print (l2)

Error:0.5712638781131371
Error:0.003431160524498867
Error:0.002728020863999013
Error:0.00524235653624164
Error:0.005193616327215113
Error:0.0051520520961577795
Output After Training:
[[0.49706129]
 [0.55020075]
 [0.60213523]
 [0.65170966]
 [0.69798445]
 [0.74029482]
 [0.77826528]
 [0.81178575]
 [0.84096259]
 [0.86605901]
 [0.88743661]
 [0.90550554]
 [0.92068649]
 [0.93338439]
 [0.94397252]
 [0.95278428]
 [0.96011068]
 [0.96620137]
 [0.97126768]
 [0.97548678]
 [0.97900614]]


#Task 4 with 3 layers


In [29]:


X = np.arange(0,4.2,0.2).reshape(21,1)

y = np.sin(X)

np.random.seed(1)

 

# randomly initialize our weights with mean 0

syn0 = 2*np.random.random((1,4)) - 1

syn1 = 2*np.random.random((4,3)) - 1
syn2 = 2*np.random.random((3,1)) - 1

 

for j in range(60000):

 

 # forward Propagation
  l0 = X
  l1 = nonlin(np.dot(l0,syn0))
  l2 = nonlin(np.dot(l1,syn1))
  l3 = nonlin(np.dot(l2,syn2))
  l3_error = y- l3


  if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l3_error))))

# backward propagation
  l3_delta = l3_error*nonlin(l3,deriv=True)  # all errors of that input layer * all derivatives of that input layer 
  l2_error = l3_delta.dot(syn2.T)
  l2_delta = l2_error*nonlin(l2,deriv=True)
  l1_error = l2_delta.dot(syn1.T)
  l1_delta = l1_error*nonlin(l1,deriv=True)



# updating weights
  syn0 += l0.T.dot(l1_delta)
  syn1 += l1.T.dot(l2_delta)
  syn2 += l3.T.dot(l3_delta)
# output layer
print('Output layer:')
print(l3)

Error:0.455723236655323
Error:0.4291838985756019
Error:0.39063702527677807
Error:0.41646909731185533
Error:0.39707783769293153
Error:0.3944021885684156
Output layer:
[[0.54494187]
 [0.54494187]
 [0.54494187]
 [0.54494187]
 [0.54494186]
 [0.54494179]
 [0.54494057]
 [0.54492669]
 [0.54480747]
 [0.54402603]
 [0.54005598]
 [0.52458014]
 [0.47998995]
 [0.40645292]
 [0.35480607]
 [0.33381583]
 [0.3259588 ]
 [0.32272194]
 [0.32121841]
 [0.3204415 ]
 [0.32000311]]
